In [3]:
!pip install --upgrade google-cloud-bigquery

Requirement already satisfied: google-cloud-bigquery in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (3.40.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.29.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-cloud-bigquery) (2.48.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-cloud-bigquery) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-cloud-bigquery) (2.8.0)
Requirement already satisfied: packaging>=24.2.0 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-cloud-bigquery) (25.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-cloud-bigquery) (2.32.5)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.72.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (6.33.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.27.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.76.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (46.0.4)
Requirement already satisfied: rsa<5,>=3.1.4 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: six>=1.5 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2025.8.3)
Requirement already satisfied: pyasn1>=0.1.3 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.2)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (2.23)

In [4]:
pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.

In [21]:
#!pip install db-dtypes pandas-gbq
#!pip install db-dtypes
#!pip install google-cloud-bigquery-storage pyarrow

from google.cloud import bigquery
import pandas as pd

client = bigquery.Client(project= 'moonlit-parsec-485600-p0')

# This query stacks the tables from different dates and unnest the stacked tables
sql = """
SELECT 
    fullVisitorId,
    date,
    p.v2ProductName, 
    p.v2ProductCategory
FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`,
    UNNEST(hits) AS h,
    UNNEST(h.product) AS p
WHERE
    _TABLE_SUFFIX BETWEEN '20170101' AND '20170630'
    AND h.transaction.transactionId is NOT NULL
"""

df = client.query(sql).to_dataframe()
print(f"Successfully pulled {len(df):,} rows!")
df.head()

C:\Users\caitc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\google\auth\_default.py:114: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Successfully pulled 32,629 rows!

         fullVisitorId      date               v2ProductName v2ProductCategory
0  0366796863244619267  20170226  Four Color Retractable Pen            Office
1  0366796863244619267  20170226  Four Color Retractable Pen            Office
2  4995606827430436569  20170226  Softsided Travel Pouch Set              Bags
3  4995606827430436569  20170226  Softsided Travel Pouch Set              Bags
4  0015950283479889703  20170226          Recycled Mouse Pad       Electronics

In [23]:
df = df.rename(columns = {
    'fullVisitorId' : 'user_id',
    'v2ProductName': 'product_name',
    'v2ProductCategory': 'product_category'
})

#df.info()

agg_df = df.groupby(['user_id','product_name']).size().reset_index(name = 'interaction_count')
agg_df

,user_id,product_name,interaction_count
0,0000213131142648941,BLM Sweatshirt,2
1,0003961110741104601,Google Laptop and Cell Phone Stickers,2
2,0003961110741104601,YouTube Custom Decals,2
3,0007933257389091624,BLM Sweatshirt,2
4,0012561433643490595,Google Kick Ball,2
...,...,...,...
13947,9990183617359422098,Windup Android,2
13948,9990797196896345494,Google Car Clip Phone Holder,2
13949,9990797196896345494,Metal Texture Roller Pen,2
13950,9990797196896345494,Switch Tone Color Crayon Pen,2
13951,9991633376050115277,BLM Sweatshirt,2

In [24]:
import os 
print(os.getcwd())

C:\Users\caitc\Senior Capstone